version: "3"
services:
  appdb:
    build: ./
    container_name: "posdb"
    environment:
      - POSTGRES_USER=test01
      - POSTGRES_PASSWORD=test01
      - POSTGRES_DB=test01
    # ttyをtrueに設定しておくと、コンテナが起動し続ける
    tty: true
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data:z
      - ./initdb:/docker-entrypoint-initdb.d